name: Update Fancyss3.0 Rules

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/fancyss_3.0_rules.yml'
      - 'fancyss_3.0_rules/rules/auto_update/*'
  workflow_dispatch:
    inputs:
      FORCE_PUSH:
        description: 'Force to push'
        required: true
        default: 'false'
  schedule:
    - cron: '50 19 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7'
      
      - name: Run update rules
        run: |
          sudo apt-get install moreutils jq
          cd fancyss_3.0_rules/rules/auto_update
          python fwlist.py
          
      - name: Commit to repo
        if: env.is_changed == '1' || github.event.inputs.FORCE_PUSH == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add fancyss_rules/.
          git commit -m "Actions Auto Update at $(date +'%Y-%m-%d %H:%M:%S')"
          git push
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          keep_minimum_runs: 30
